tournament:
    resource: "@TournamentBundle/Controller/"
    type:     annotation
    prefix:   /

register:
    resource: "@RegisterBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
